### PR TITLE
Feature update to the Mod

### PR DESCRIPTION
**Pull request by themg95**
Hello,
This mod is one of my favorite mods and i wanted some features in it. I saw it is now not updated so i updated it.

**This is update brings 2 new features to the mod:**

1) Ability to select after which message to send the message (seconds in `The game starts in [seconds] seconds!` message)

2) Custom delay to send the message after. This is also compatible with the first addition.

Note: When merging some credit things and some spelling need to change a little bit

### CODE REVIEW

**Comment by ghost** [comment]
this pr is gonna have to wait until modcore 2 as there's no other way of releasing this atm, but until then there's a few issues
fix your continuation indent being 8 instead of 4, causes big ugly spaces between lines (best example is the config file)
rename `setAutoGLTime` to `getDelayTime`
remove the edit from the description, the url, and add yourself to the author list instead.

**Comment by themg95** [comment]
Thanks for the reply. I will fix these.

**Comment by themg95** [comment]
Hello again,
I made the changes that you requested. It is now ready to merge when ModCore 2.0 comes out.

**Comment by Sychic** [comment]
Mod is EOL

**Pull request closed without merging**
